# Generated by Django 4.0 on 2022-01-27 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dossier', models.CharField(help_text='Numero dossier du candidat', max_length=45, verbose_name='Numero Dossier')),
                ('annee', models.PositiveBigIntegerField(help_text='Annee de candidature', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2035)], verbose_name='Annee')),
                ('nom', models.CharField(help_text='Nom du candidat', max_length=245, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prenom du candidat', max_length=245, verbose_name='Prenom')),
                ('date_naissance', models.DateField(blank=True, help_text='Date de naissance', null=True, verbose_name='Date de naissance')),
                ('nni', models.CharField(help_text='NNI du candidat', max_length=10, verbose_name='NNI')),
                ('aptitude', models.CharField(blank=True, choices=[('I', 'Inapte'), ('A', 'Apte')], help_text='Aptitude du candidat', max_length=10, null=True, verbose_name='Aptitude')),
                ('type_candidature', models.CharField(blank=True, choices=[('CL', 'CL'), ('CP', 'CP'), ('OF', 'OF')], help_text='Type de Candidature', max_length=10, null=True, verbose_name='Type de Candidature')),
            ],
            options={
                'ordering': ['annee', 'num_dossier'],
            },
        ),
        migrations.CreateModel(
            name='CentreExam',
            fields=[
                ('code', models.CharField(help_text="Code du Centre d'Examen", max_length=45, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('code', models.CharField(help_text="Code de l'Etablissement", max_length=45, primary_key=True, serialize=False, verbose_name='Code')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code Examen', max_length=45, verbose_name='Code')),
                ('serie', models.CharField(help_text='Serie Examen', max_length=45, verbose_name='Serie')),
            ],
            options={
                'ordering': ['serie', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.PositiveIntegerField(help_text='Code de la Wilaya', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Code')),
                ('nom', models.CharField(blank=True, help_text='Nom de la Wilaya', max_length=200, null=True, verbose_name='Nom')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('code', 'serie'), name='unique_code_serie'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='wilaya',
            field=models.ForeignKey(help_text="Wilaya de l'Etablissement", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bac.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AddField(
            model_name='centreexam',
            name='wilaya',
            field=models.ForeignKey(help_text="Wilaya du Centre d'Examen", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bac.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='centre_exam',
            field=models.ForeignKey(help_text='Centre Examen du candidat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bac.centreexam', verbose_name='Centre Examen'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='etablissement',
            field=models.ForeignKey(help_text='Etablissement du candidat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bac.etablissement', verbose_name='Etablissement'),
        ),
        migrations.AddConstraint(
            model_name='candidat',
            constraint=models.UniqueConstraint(fields=('annee', 'num_dossier'), name='unique_annee_num_dossier'),
        ),
    ]
