# Generated by Django 4.0 on 2022-01-27 00:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='id',
            field=models.CharField(help_text='ID Candidat', max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(help_text='ID Examen', max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('decision', models.CharField(max_length=245)),
                ('candidat', models.ForeignKey(help_text='Candidat', on_delete=django.db.models.deletion.CASCADE, to='bac.candidat', verbose_name='Candidat')),
                ('examen', models.ForeignKey(help_text='Examen', on_delete=django.db.models.deletion.CASCADE, to='bac.exam', verbose_name='Examen')),
            ],
            options={
                'ordering': ['examen', 'candidat'],
            },
        ),
        migrations.AddConstraint(
            model_name='resultat',
            constraint=models.UniqueConstraint(fields=('examen', 'candidat'), name='unique_examen_candidat'),
        ),
    ]
