# Generated by Django 4.0 on 2022-01-27 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bac', '0002_alter_candidat_id_alter_exam_id_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], help_text='Genre', max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.PositiveIntegerField(help_text='Code de la Wilaya', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Code Wilaya'),
        ),
    ]
